# Generated by Django 4.2.5 on 2023-09-10 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alt_text', models.CharField(max_length=100)),
                ('image_src', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uploads')),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picApp.imagecategory')),
            ],
        ),
    ]
