# Generated by Django 4.2.5 on 2023-09-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image_src',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
