# Generated by Django 4.2.5 on 2023-09-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picApp', '0002_alter_imageupload_image_src_alter_imageupload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='alt_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image_src',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
